### ISSUE TITLE
[Feature suggestion] Implement property checkers

### ISSUE THREAD

**Issue by DominikPeters** [pbvoting/pabutools#10]
The `abcvoting` package supports checking whether a given committee satisfies EJR and friends. The same could be useful in this package, including

* EJR and EJR1 ([paper 1](https://dominik-peters.de/publications/equal-shares.pdf), [paper 2](https://arxiv.org/abs/2302.03672))
* EJR+ up to any project (for cost utilities) ([paper](https://arxiv.org/abs/2302.01989), Section 5.2)
* core
* Pareto optimality

**Comment by Simon-Rey** [comment]
That's also WIP but in the analysis module we have a lot of things already: Core, Core1, CoreX, EJR, EJR1, EJRX, PJR, PJR1, PJRX.

**Comment by DominikPeters** [comment]
Ha I need to start looking at the code not the documentation 🤭

**Comment by Simon-Rey** [comment]
For now it's implemented as brute force over all cohesive groups. That is not efficient at all, there could be ILP formulations to make it faster (or other algorithms).

**Comment by Simon-Rey** [comment]
> Ha I need to start looking at the code not the documentation 🤭

Yeah, the writing pb file was a real mistake from my side, this one is more WIP so I don't advertise it yet ^^
