### ISSUE TITLE
MES is slow to compute

### ISSUE THREAD

**Issue by DominikPeters** [pbvoting/pabutools#7]
MES with Add1 takes about 100x longer to compute than with the code snippet on equalshares.net.

I've profiled the code, and the data I collected suggests that the code spends 90% of its time on two things:

(1) Computing the scores of all candidates
https://github.com/pbvoting/pabutools/blob/63f69b3153f719e493f1519f23aa4cfe29e93937/pabutools/rules/mes.py#L231

(2) Computing the supporters of all candidates
https://github.com/pbvoting/pabutools/blob/63f69b3153f719e493f1519f23aa4cfe29e93937/pabutools/rules/mes.py#L243-L246

Internally these operations appear to be slow due to lookups of precomputed satisfaction scores in `additivesatisfaction.py`. It is possible (but I haven't tried) that this could be made faster by not using projects as keys of the dictionary, and instead using `project.name` as the key.
https://github.com/pbvoting/pabutools/blob/63f69b3153f719e493f1519f23aa4cfe29e93937/pabutools/election/satisfaction/additivesatisfaction.py#L120-L121

But maybe it is better to avoid recomputing (1) and (2) in every Add1 iteration. Maybe project objects can store their scores according to whatever satisfaction function?

## Aside
In case it is useful to you, here is how I profiled it:

I made a file `run-mes.py` with
```python
from pabutools.election import parse_pabulib, Cost_Sat
from pabutools.rules import method_of_equal_shares, exhaustion_by_budget_increase

instance, profile = parse_pabulib("poland_wieliczka_2023.pb")

winners = exhaustion_by_budget_increase(
    instance, 
    profile, 
    rule=method_of_equal_shares, 
    rule_params={'sat_class': Cost_Sat}, 
    budget_step=10*len(profile))

print(len(winners))
```
Then I run
```bash
python -m cProfile -o pabutools.prof run-mes.py
```
This stores profile information in the file `pabutools.prof`. One can visualize this information by running
```bash
pip install snakeviz
snakeviz pabutools.prof
```
<img width="500" alt="image" src="https://github.com/pbvoting/pabutools/assets/3543224/33526d4d-7e36-41a4-a7ad-498be3e7384a">

**Comment by Simon-Rey** [comment]
I'm on it but it's tricky. Feels like the satisfaction function structure is too heavy. For now I'm only focusing on MES without Add1, which already takes 3 seconds to compute, i.e., too much!

**Comment by Simon-Rey** [comment]
So I changed some things and optimised a bit everything, it's now faster than the JS which is good. I will push when I'm done with other problems.

I am a bit confused with the code snippet on equalshares.net, especially for the scoring ballots. Is this part really correct?
`for i in approvers[c]:
                # compute payment if remaining approvers pay proportional to their utility
                payment_factor = (cost[c] - paid_so_far) / denominator
                eff_vote_count = cost[c] / payment_factor
                if payment_factor * u[i][c] > budget[i]:
                    # i cannot afford the payment, so pays entire remaining budget
                    paid_so_far += budget[i]
                    denominator -= u[i][c]
                else:
                    # i (and all later approvers) can afford the payment; stop here
                    remaining[c] = eff_vote_count
                    if eff_vote_count > best_eff_vote_count:
                        best_eff_vote_count = eff_vote_count
                        best = [c]
                    elif eff_vote_count == best_eff_vote_count:
                        best.append(c)
                    break`
Do we really want to divide cost/rho for the effective vote count? I find it hard to relate this to Definition 1 in https://dominik-peters.de/publications/equal-shares.pdf.
@DominikPeters can you confirm/explain?

**Comment by Simon-Rey** [comment]
With what I have now pushed, here is how to be the fastest (still not crazily fast):

```
winners_slow = method_of_equal_shares(
        instance,
        profile.as_multiprofile(),
        sat_class=Cost_Sat,
        budget_step=len(profile),
    )
```

**Comment by Simon-Rey** [comment]
> So I changed some things and optimised a bit everything, it's now faster than the JS which is good. I will push when I'm done with other problems.
> 
> I am a bit confused with the code snippet on equalshares.net, especially for the scoring ballots. Is this part really correct?
> 
> ```
> for i in approvers[c]:
>     # compute payment if remaining approvers pay proportional to their utility
>     payment_factor = (cost[c] - paid_so_far) / denominator
>     eff_vote_count = cost[c] / payment_factor
>     if payment_factor * u[i][c] > budget[i]:
>         # i cannot afford the payment, so pays entire remaining budget
>         paid_so_far += budget[i]
>         denominator -= u[i][c]
>     else:
>         # i (and all later approvers) can afford the payment; stop here
>         remaining[c] = eff_vote_count
>         if eff_vote_count > best_eff_vote_count:
>             best_eff_vote_count = eff_vote_count
>             best = [c]
>         elif eff_vote_count == best_eff_vote_count:
>             best.append(c)
>         break
> ```
> 
> Do we really want to divide cost/rho for the effective vote count? I find it hard to relate this to Definition 1 in https://dominik-peters.de/publications/equal-shares.pdf. @DominikPeters can you confirm/explain?

Now that I know it's cost * utility, then all good, it works as expected!

**Comment by Simon-Rey** [comment]
Ok I've now deployed a new implementation for MES, much faster (roughly 4-5 times faster with iterated). See the updated docs for the details. Note the disappearance of mes_iterated and mes_completed for the package.

**Comment by DominikPeters** [comment]
Thank you, well done! This is now usable and competitive with from-scratch python implementations.

(Javascript is still much faster, but I'd blame python for that. Zielony Milion with iterated MES can be done in 0.2s with JS, while pabutools 1.0.12 takes 5.2s.)

**Comment by Simon-Rey** [comment]
Yes the difference is still crazy. Maybe at some point someone could look into doing this more efficiently (maybe in CPython) but I think for now it's mostly fine.

**Comment by Simon-Rey** [comment]
Just to see the difference, I know coded a very basic version in C, with the instance hardcoded. MES iterated takes 0.15439s with terrible data structure (fixed size array for the approval ballots despite a lot of 0s). I'm attaching it in case ;)
[MES_C.zip](https://github.com/pbvoting/pabutools/files/13190722/MES_C.zip)

**Comment by Simon-Rey** [comment]
And the Python code to generate the election in C (that then needs to be compiled with the whole thing):

```
file_root = "lask"
file_name = file_root + ".c"
with open(file_name, "w") as f:
    f.write("int " + file_root + "NumVoters() {\n\t return " + f"{profile.num_ballots()};\n" + "}\n")

    f.write("int " + file_root + "NumProjects () {\n\treturn " + f"{len(instance)};\n" + "}\n")

    f.write("void " + file_root + "Utilities(double* utilities) {\n")
    index = 0
    for sat in profile.as_sat_profile(SAT_CLASS):
        for proj in projects:
            f.write(f"\tutilities[{index}] = {float(sat.sat_project(proj))};\n")
            index += 1
    f.write("}\n")

    f.write("void " + file_root + "Costs(double* costs) {\n")
    for j, proj in enumerate(projects):
        f.write(f"\tcosts[{j}] = {float(proj.cost)};\n")
    f.write("}\n")

    f.write("void " + file_root + "PabulibIDs(int* pabulibIDs) {\n")
    for j, proj in enumerate(projects):
        try:
            name = int(proj.name)
        except Exception as e:
            if isinstance(proj.name, str) and len(proj.name) == 1:
                name = ord(proj.name) - 97
            else:
                name = proj.name
        f.write(f"\tpabulibIDs[{j}] = {name};\n")
    f.write("}\n")

    f.write("double " + file_root + "BudgetLimit () {\n\treturn " + f"{float(instance.budget_limit)};\n" + "}\n") 
```
