### ISSUE TITLE
[Feature] pabulib export

### ISSUE THREAD

**Issue by DominikPeters** [pbvoting/pabutools#8]
It could be nice to have to have a function that given an `instance` and a `profile` produces a `.pb` file as a string or saves it as a file (both of these would be useful).

**Comment by Simon-Rey** [comment]
Something like the pabutools.election.pabulib.write_pabulib ? The function is there but has not been advertised ^^

**Comment by Simon-Rey** [comment]
I've now updated the docs and split the function between the str representation and the file writing. I'll close this, re-open if there is something else you need Dominik ;)

**Comment by DominikPeters** [comment]
Thanks Simon!

**Comment by DominikPeters** [comment]
Can you make a release? Thanks!

**Comment by Simon-Rey** [comment]
Yes, sorry. It's done now.
